-- RoamSonio Phase 2B: Master read-only directory + support foundation
-- Requires Phase 2A migration 20261003_roamsonio_admin_foundation.sql.

-- Harden approval RPCs so browser calls cannot depend on direct table privileges.
create or replace function public.roamsonio_submit_approval(
  p_request_type text,
  p_entity_type text,
  p_entity_id text,
  p_reason text,
  p_proposed_changes jsonb,
  p_required_role text default 'admin'
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_level integer;
  v_required integer;
begin
  v_level := public.roamsonio_my_admin_level();
  v_required := public.roamsonio_role_level(p_required_role);
  if v_level < 10 then raise exception 'Administrator access required'; end if;
  if v_required < 20 then v_required := 20; end if;

  insert into public.roamsonio_approval_requests(
    submitted_by,request_type,entity_type,entity_id,reason,proposed_changes,required_role
  ) values (
    auth.uid(),p_request_type,p_entity_type,p_entity_id,p_reason,
    coalesce(p_proposed_changes,'{}'::jsonb),p_required_role
  ) returning id into v_id;

  update public.roamsonio_approval_requests
  set request_code='RS-'||lpad(v_id::text,6,'0'),updated_at=now()
  where id=v_id;

  insert into public.roamsonio_admin_audit_log(actor_user_id,action,approval_request_id,details)
  values(auth.uid(),'approval_submitted',v_id,
    jsonb_build_object('request_type',p_request_type,'entity_type',p_entity_type));

  return v_id;
end;
$$;

create or replace function public.roamsonio_decide_approval(
  p_request_id bigint,
  p_decision text,
  p_note text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  r public.roamsonio_approval_requests%rowtype;
  v_level integer;
  v_required integer;
begin
  select * into r from public.roamsonio_approval_requests
  where id=p_request_id for update;
  if not found then raise exception 'Approval request not found'; end if;
  if r.status <> 'pending' then raise exception 'Approval request is no longer pending'; end if;
  if r.submitted_by=auth.uid() then raise exception 'The requester cannot approve or reject their own request'; end if;
  v_level:=public.roamsonio_my_admin_level();
  v_required:=public.roamsonio_role_level(r.required_role);
  if v_level<v_required then raise exception 'Insufficient approval level'; end if;
  if p_decision not in ('approved','rejected','needs_clarification') then raise exception 'Invalid decision'; end if;

  update public.roamsonio_approval_requests
  set status=p_decision,decided_by=auth.uid(),decided_at=now(),
      decision_note=p_note,updated_at=now()
  where id=p_request_id;

  insert into public.roamsonio_admin_audit_log(actor_user_id,action,approval_request_id,details)
  values(auth.uid(),'approval_'||p_decision,p_request_id,jsonb_build_object('note',p_note));
end;
$$;

revoke all on function public.roamsonio_submit_approval(text,text,text,text,jsonb,text)
  from public, anon, authenticated;
revoke all on function public.roamsonio_decide_approval(bigint,text,text)
  from public, anon, authenticated;
grant execute on function public.roamsonio_submit_approval(text,text,text,text,jsonb,text) to authenticated;
grant execute on function public.roamsonio_decide_approval(bigint,text,text) to authenticated;
revoke insert on public.roamsonio_approval_requests from authenticated;

-- Support requests. Users can create/read their own requests.
create table if not exists public.roamsonio_support_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null,
  category text not null default 'general'
    check (category in ('general','account','trip','family','sharing','billing','bug','complaint','other')),
  description text not null,
  priority text not null default 'normal'
    check (priority in ('low','normal','high','urgent')),
  status text not null default 'open'
    check (status in ('open','in_progress','waiting_on_user','resolved','closed')),
  assigned_to uuid references auth.users(id) on delete set null,
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists roamsonio_support_requests_user_idx
  on public.roamsonio_support_requests(user_id,created_at desc);
create index if not exists roamsonio_support_requests_status_idx
  on public.roamsonio_support_requests(status,priority,created_at desc);

alter table public.roamsonio_support_requests enable row level security;

drop policy if exists "support own read" on public.roamsonio_support_requests;
create policy "support own read" on public.roamsonio_support_requests
for select to authenticated
using (user_id=auth.uid());

drop policy if exists "support own insert" on public.roamsonio_support_requests;
create policy "support own insert" on public.roamsonio_support_requests
for insert to authenticated
with check (user_id=auth.uid());

drop policy if exists "support admin read" on public.roamsonio_support_requests;
create policy "support admin read" on public.roamsonio_support_requests
for select to authenticated
using (
  public.roamsonio_my_admin_level() >= 10
);

grant select,insert on public.roamsonio_support_requests to authenticated;

-- Read-only Master directory functions. These require both Master role and AAL2.
create or replace function public.roamsonio_admin_users()
returns table(
  user_id uuid,
  email text,
  display_name text,
  created_at timestamptz,
  last_sign_in_at timestamptz,
  email_confirmed_at timestamptz,
  admin_role text,
  admin_active boolean
)
language plpgsql
security definer
set search_path = ''
stable
as $$
begin
  if not public.roamsonio_is_master_admin()
     or coalesce(auth.jwt()->>'aal','aal1') <> 'aal2' then
    raise exception 'Master Admin MFA verification required';
  end if;
  return query
  select u.id,u.email,
    coalesce(nullif(u.raw_user_meta_data->>'display_name',''),
             nullif(u.raw_user_meta_data->>'full_name',''),'')::text,
    u.created_at,u.last_sign_in_at,u.email_confirmed_at,
    r.role,r.active
  from auth.users u
  left join public.roamsonio_admin_roles r on r.user_id=u.id
  order by u.created_at desc;
end;
$$;

create or replace function public.roamsonio_admin_trips()
returns table(
  trip_id uuid,
  owner_id uuid,
  owner_email text,
  owner_name text,
  trip_name text,
  visibility text,
  surprise_mode boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
stable
as $$
begin
  if not public.roamsonio_is_master_admin()
     or coalesce(auth.jwt()->>'aal','aal1') <> 'aal2' then
    raise exception 'Master Admin MFA verification required';
  end if;
  return query
  select t.id,t.owner_id,u.email,
    coalesce(nullif(u.raw_user_meta_data->>'display_name',''),
             nullif(u.raw_user_meta_data->>'full_name',''),'')::text,
    t.name,t.visibility,t.surprise_mode,t.created_at
  from public.trips t
  left join auth.users u on u.id=t.owner_id
  order by t.created_at desc;
end;
$$;

create or replace function public.roamsonio_admin_families()
returns table(
  family_id uuid,
  family_name text,
  owner_id uuid,
  owner_email text,
  owner_name text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
stable
as $$
begin
  if not public.roamsonio_is_master_admin()
     or coalesce(auth.jwt()->>'aal','aal1') <> 'aal2' then
    raise exception 'Master Admin MFA verification required';
  end if;
  return query
  select f.id,f.name,f.owner_id,u.email,
    coalesce(nullif(u.raw_user_meta_data->>'display_name',''),
             nullif(u.raw_user_meta_data->>'full_name',''),'')::text,
    f.created_at
  from public.families f
  left join auth.users u on u.id=f.owner_id
  order by f.created_at desc;
end;
$$;

create or replace function public.roamsonio_admin_support_requests()
returns table(
  request_id bigint,
  user_id uuid,
  user_email text,
  user_name text,
  subject text,
  category text,
  description text,
  priority text,
  status text,
  assigned_to uuid,
  admin_note text,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = ''
stable
as $$
begin
  if not public.roamsonio_is_master_admin()
     or coalesce(auth.jwt()->>'aal','aal1') <> 'aal2' then
    raise exception 'Master Admin MFA verification required';
  end if;
  return query
  select s.id,s.user_id,u.email,
    coalesce(nullif(u.raw_user_meta_data->>'display_name',''),
             nullif(u.raw_user_meta_data->>'full_name',''),'')::text,
    s.subject,s.category,s.description,s.priority,s.status,s.assigned_to,
    s.admin_note,s.created_at,s.updated_at
  from public.roamsonio_support_requests s
  left join auth.users u on u.id=s.user_id
  order by s.created_at desc;
end;
$$;

revoke all on function public.roamsonio_admin_users() from public,anon,authenticated;
revoke all on function public.roamsonio_admin_trips() from public,anon,authenticated;
revoke all on function public.roamsonio_admin_families() from public,anon,authenticated;
revoke all on function public.roamsonio_admin_support_requests() from public,anon,authenticated;
grant execute on function public.roamsonio_admin_users() to authenticated;
grant execute on function public.roamsonio_admin_trips() to authenticated;
grant execute on function public.roamsonio_admin_families() to authenticated;
grant execute on function public.roamsonio_admin_support_requests() to authenticated;
