-- RoamSonio Admin Foundation
-- Phase 2A: role hierarchy + approval workflow foundation.
-- SAFE BY DESIGN:
--   * No existing user/trip/family tables are modified.
--   * No existing application data is exposed.
--   * Master Admin is bootstrapped manually from the Supabase SQL Editor.
--   * Approval records are separate from live business data until a later phase wires
--     approved changes into specific, validated RPCs.
--
-- Roles:
--   support_admin = level 10
--   admin         = level 20
--   senior_admin  = level 30
--   master_admin  = level 100
--
-- Important: do NOT use user_metadata for authorization.

create table if not exists public.roamsonio_admin_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('support_admin','admin','senior_admin','master_admin')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists roamsonio_admin_roles_role_idx
  on public.roamsonio_admin_roles(role);

create table if not exists public.roamsonio_approval_requests (
  id bigint generated by default as identity primary key,
  request_code text unique,
  submitted_by uuid not null references auth.users(id) on delete restrict,
  request_type text not null,
  entity_type text not null,
  entity_id text,
  reason text,
  proposed_changes jsonb not null default '{}'::jsonb,
  required_role text not null default 'admin'
    check (required_role in ('support_admin','admin','senior_admin','master_admin')),
  status text not null default 'pending'
    check (status in ('pending','approved','rejected','needs_clarification','cancelled')),
  decided_by uuid references auth.users(id) on delete restrict,
  decided_at timestamptz,
  decision_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (decided_by is null or decided_by <> submitted_by)
);

create index if not exists roamsonio_approval_requests_status_idx
  on public.roamsonio_approval_requests(status, created_at desc);

create index if not exists roamsonio_approval_requests_submitter_idx
  on public.roamsonio_approval_requests(submitted_by, created_at desc);

create table if not exists public.roamsonio_admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_user_id uuid references auth.users(id) on delete set null,
  approval_request_id bigint references public.roamsonio_approval_requests(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists roamsonio_admin_audit_log_created_idx
  on public.roamsonio_admin_audit_log(created_at desc);

-- Role levels are deliberately centralized so approval rules cannot depend on UI code.
create or replace function public.roamsonio_role_level(p_role text)
returns integer
language sql
immutable
as $$
  select case p_role
    when 'support_admin' then 10
    when 'admin' then 20
    when 'senior_admin' then 30
    when 'master_admin' then 100
    else 0
  end;
$$;

-- SECURITY DEFINER is used only for controlled role lookup.
-- The function reads the protected admin-role table and exposes only the caller's
-- own role level.
create or replace function public.roamsonio_my_admin_role()
returns text
language sql
security definer
set search_path = public
stable
as $$
  select role
  from public.roamsonio_admin_roles
  where user_id = auth.uid()
    and active = true
  limit 1;
$$;

create or replace function public.roamsonio_my_admin_level()
returns integer
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(public.roamsonio_role_level(
    (select role from public.roamsonio_admin_roles
     where user_id = auth.uid() and active = true limit 1)
  ), 0);
$$;

-- Returns true only for an active Master Admin.
create or replace function public.roamsonio_is_master_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.roamsonio_admin_roles
    where user_id = auth.uid()
      and role = 'master_admin'
      and active = true
  );
$$;

-- Bootstrap is intentionally NOT executable by normal users.
-- Run this manually in Supabase SQL Editor with YOUR auth.users UUID.
create or replace function public.roamsonio_bootstrap_master_admin(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from auth.users where id = p_user_id) then
    raise exception 'User does not exist in auth.users';
  end if;

  if exists (
    select 1 from public.roamsonio_admin_roles
    where role = 'master_admin' and active = true
  ) then
    raise exception 'An active Master Admin already exists';
  end if;

  insert into public.roamsonio_admin_roles(user_id, role)
  values (p_user_id, 'master_admin')
  on conflict (user_id)
  do update set role='master_admin', active=true, updated_at=now();
end;
$$;

revoke all on function public.roamsonio_bootstrap_master_admin(uuid)
  from public, anon, authenticated;

-- Approval submission. A user must already be an active admin.
create or replace function public.roamsonio_submit_approval(
  p_request_type text,
  p_entity_type text,
  p_entity_id text,
  p_reason text,
  p_proposed_changes jsonb,
  p_required_role text default 'admin'
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_id bigint;
  v_level integer;
  v_required integer;
begin
  v_level := public.roamsonio_my_admin_level();
  v_required := public.roamsonio_role_level(p_required_role);

  if v_level < 10 then
    raise exception 'Administrator access required';
  end if;

  if v_required < 20 then
    v_required := 20;
  end if;

  if v_level < v_required and v_level < 10 then
    raise exception 'Insufficient permission';
  end if;

  insert into public.roamsonio_approval_requests(
    submitted_by, request_type, entity_type, entity_id, reason,
    proposed_changes, required_role
  )
  values (
    auth.uid(), p_request_type, p_entity_type, p_entity_id, p_reason,
    coalesce(p_proposed_changes, '{}'::jsonb), p_required_role
  )
  returning id into v_id;

  update public.roamsonio_approval_requests
  set request_code = 'RS-' || lpad(v_id::text, 6, '0')
  where id = v_id;

  insert into public.roamsonio_admin_audit_log(
    actor_user_id, action, approval_request_id, details
  )
  values (
    auth.uid(), 'approval_submitted', v_id,
    jsonb_build_object('request_type',p_request_type,'entity_type',p_entity_type)
  );

  return v_id;
end;
$$;

-- Approve/reject/clarify. The submitter can NEVER decide their own request.
create or replace function public.roamsonio_decide_approval(
  p_request_id bigint,
  p_decision text,
  p_note text default null
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  r public.roamsonio_approval_requests%rowtype;
  v_level integer;
  v_required integer;
begin
  select * into r
  from public.roamsonio_approval_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception 'Approval request not found';
  end if;

  if r.status <> 'pending' then
    raise exception 'Approval request is no longer pending';
  end if;

  if r.submitted_by = auth.uid() then
    raise exception 'The requester cannot approve or reject their own request';
  end if;

  v_level := public.roamsonio_my_admin_level();
  v_required := public.roamsonio_role_level(r.required_role);

  if v_level < v_required then
    raise exception 'Insufficient approval level';
  end if;

  if p_decision not in ('approved','rejected','needs_clarification') then
    raise exception 'Invalid decision';
  end if;

  update public.roamsonio_approval_requests
  set status=p_decision,
      decided_by=auth.uid(),
      decided_at=now(),
      decision_note=p_note,
      updated_at=now()
  where id=p_request_id;

  insert into public.roamsonio_admin_audit_log(
    actor_user_id, action, approval_request_id, details
  )
  values (
    auth.uid(), 'approval_' || p_decision, p_request_id,
    jsonb_build_object('note',p_note)
  );
end;
$$;

alter table public.roamsonio_admin_roles enable row level security;
alter table public.roamsonio_approval_requests enable row level security;
alter table public.roamsonio_admin_audit_log enable row level security;

-- Admin roles: admins may see their own role. Master Admin can see the full
-- role roster. Nobody can directly insert/update/delete roles from the browser.
drop policy if exists "admin roles self read" on public.roamsonio_admin_roles;
create policy "admin roles self read"
on public.roamsonio_admin_roles
for select
to authenticated
using (user_id = auth.uid() or public.roamsonio_is_master_admin());

drop policy if exists "approval submitter or approver read" on public.roamsonio_approval_requests;
create policy "approval submitter or approver read"
on public.roamsonio_approval_requests
for select
to authenticated
using (
  submitted_by = auth.uid()
  or (
    public.roamsonio_my_admin_level() >=
      public.roamsonio_role_level(required_role)
  )
);

drop policy if exists "approval insert by admin" on public.roamsonio_approval_requests;
create policy "approval insert by admin"
on public.roamsonio_approval_requests
for insert
to authenticated
with check (
  submitted_by = auth.uid()
  and public.roamsonio_my_admin_level() >= 10
);

-- Direct updates/deletes are intentionally denied. All decisions go through
-- roamsonio_decide_approval(), which enforces separation of duties.
drop policy if exists "no direct approval update" on public.roamsonio_approval_requests;
drop policy if exists "no direct approval delete" on public.roamsonio_approval_requests;

drop policy if exists "audit master read" on public.roamsonio_admin_audit_log;
create policy "audit master read"
on public.roamsonio_admin_audit_log
for select
to authenticated
using (public.roamsonio_is_master_admin());

-- Audit rows are written by controlled functions; no direct browser insert/update/delete.
drop policy if exists "no direct audit insert" on public.roamsonio_admin_audit_log;

grant select on public.roamsonio_admin_roles to authenticated;
grant select, insert on public.roamsonio_approval_requests to authenticated;
grant select on public.roamsonio_admin_audit_log to authenticated;
grant execute on function public.roamsonio_my_admin_role() to authenticated;
grant execute on function public.roamsonio_my_admin_level() to authenticated;
grant execute on function public.roamsonio_is_master_admin() to authenticated;
grant execute on function public.roamsonio_submit_approval(text,text,text,text,jsonb,text) to authenticated;
grant execute on function public.roamsonio_decide_approval(bigint,text,text) to authenticated;

-- NOTE FOR PHASE 2B:
-- Specific business-data changes must be applied through dedicated RPCs that:
--   1) verify approval status,
--   2) verify the approver is not the requester,
--   3) validate the proposed change against the target table,
--   4) apply the change atomically,
--   5) write an immutable audit event.
